apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: nginx
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
  hostnames:
    - "tenant-c.traefik.local"
  rules:
    - backendRefs:
        - kind: Service
          name: nginx-x-default-x-vcluster-c
          namespace: vcluster-c
          port: 80
