apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vcluster-b
spec:
  chart:
    spec:
      chart: vcluster
      sourceRef:
        kind: HelmRepository
        name: loft
      version: "0.30.4"
  interval: 5m
  values:
    controlPlane:
      service:
        annotations:
          metallb.universe.tf/loadBalancerIPs: 172.18.0.211
        spec:
          type: LoadBalancer
      distro:
        k3s:
          enabled: true
          extraArgs:
            - --tls-san=172.18.0.211
      statefulSet:
        env:
          - name: K3S_KUBECONFIG_OUTPUT
            value: /data/k3s-config/kube-config.yaml
          - name: K3S_KUBECONFIG_MODE
            value: "644"
    sync:
      toHost:
        pods:
          enabled: true
        services:
          enabled: true
        configMaps:
          enabled: true
        secrets:
          enabled: true
        endpoints:
          enabled: true
        persistentVolumeClaims:
          enabled: true
      fromHost:
        nodes:
          enabled: true
          syncBackChanges: false
        storageClasses:
          enabled: true
