apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
      version: "1.19.2"
  interval: 2m
  values:
    installCRDs: true
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
        prometheusInstance: kube-prometheus-stack
        labels:
          release: kube-prometheus-stack
    featureGates: "ExperimentalGatewayAPISupport=true"